name: Deploy to Pages

on:
  push:
    paths:
    - ".github/workflows/static.yml"
    
  schedule:
  - cron: "0 0 * * 0"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout movie-web
        uses: actions/checkout@v4
        with:
          repository: "movie-web/movie-web"
          ref: master
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Customize instance
        run: |
          sed -i "s|https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap|https://fonts.lonelil.com/fonts/Satoshi/use.min.css|g" index.html
          sed -i "s|Open Sans|Satoshi Variable|g" tailwind.config.ts
          sed -i "s|w185|original|g" src/backend/metadata/tmdb.ts
          sed -i 's/Math.floor(Math.random() \* 600) === 1/true/g' src/components/utils/Lightbar.tsx
        if: github.repository == 'lonelil/mw-selfhost'
      - name: Build
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          pnpm i
          pnpm build
          cp dist/index.html dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
