name: Deploy to Pages

on:
  schedule:
  - cron: "0 0 * * 0"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Download latest release
        run: |
          download_url=$(curl -s https://api.github.com/repos/movie-web/movie-web/releases/latest | grep 'browser_' | cut -d\" -f4 | grep 'movie-web.zip')
          if [ -z "$download_url" ]; then
            echo "movie-web.zip not found in the latest release"
            exit 1
          fi
          wget $download_url
      - name: Unzip
        run: |
          mkdir movie-web
          unzip movie-web.zip -d movie-web
      - name: Edit config
        run: |
          decoded_config=$(base64 --decode config.txt)
          echo "$decoded_config" > movie-web/config.js
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'movie-web'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
